version: '3.8'

services:
  docscheduler-api:
    image: $ECR_REPOSITORY:$COMMIT_HASH
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "80:3000"