// Set test environment variables before any imports
process.env.NODE_ENV = 'test'
process.env.PORT = '3001'
process.env.PROJECT_NAME = 'template-nodejs-test'
process.env.COMMIT_HASH = 'TEST'
process.env.API_BASE_URL = 'http://localhost:3001'
process.env.WEB_URL = 'http://localhost:3002'
process.env.DATABASE_URL = 'postgresql://postgres:newpassword@localhost:5432/template_nodejs_test?schema=public'
process.env.DOCS_USER = 'test'
process.env.DOCS_PASSWORD = 'test'
process.env.ACCESS_TOKEN_SECRET = 'test-access-token-secret'
process.env.REFRESH_TOKEN_SECRET = 'test-refresh-token-secret'
process.env.ACCESS_TOKEN_EXPIRES_IN = '15'
process.env.REFRESH_TOKEN_EXPIRES_IN = '10080'
process.env.LOG_REQUESTS = 'false'
process.env.LOG_TO_CONSOLE = 'false'
process.env.REDIS_URL = ''
process.env.RATE_LIMITER_DURATION_IN_SECONDS = '60'
process.env.RATE_LIMITER_POINTS = '1000'
process.env.RATE_LIMITER_BLOCKING_DURATION_IN_SECONDS = '0'
process.env.LOGIN_LIMITER_POINTS = '1000'
process.env.LOGIN_LIMITER_DURATION_IN_SECONDS = '60'
process.env.LOGIN_LIMITER_BLOCKING_DURATION_IN_SECONDS = '0'
process.env.AWS_ACCESS_KEY = ''
process.env.AWS_SECRET = ''
process.env.AWS_REGION = 'us-east-1'
process.env.SES_VERIFIED_MAIL = 'noreply@test.com'
process.env.SMS_VERIFIED_PHONE_NUMBER = ''
process.env.GOOGLE_CLOUD_PROJECT_ID = ''
process.env.GOOGLE_SERVICE_ACCOUNT_KEY_LOCATION = ''
process.env.GOOGLE_CLOUD_STORAGE_BUCKET_NAME = ''
process.env.SALT_ROUNDS = '10'
process.env.ALLOWED_ORIGINS = 'http://localhost:3002'

// Increase timeout for async operations
jest.setTimeout(30000)
