name: "Setup Environment"
description: "Sets up environment variables and creates .env from env.template"
inputs: {}
runs:
  using: "composite"
  steps:
    - run: |
        set -euo pipefail
        # Determine environment and copy appropriate .env file
        if [ "${GITHUB_REF##*/}" == "main" ]; then
          ENV_SUFFIX="PRODUCTION"
          cp "$GITHUB_WORKSPACE/.env.production" .env
        else
          ENV_SUFFIX="STAGING"
          cp "$GITHUB_WORKSPACE/.env.staging" .env
        fi
        ENVIRONMENT=$(echo "$ENV_SUFFIX" | tr '[:upper:]' '[:lower:]')
        COMMIT_HASH="${{ github.sha }}"

        # List of environment variable names
        VARS=(
          PROJECT_NAME NODE_ENV PORT ACCESS_TOKEN_SECRET REFRESH_TOKEN_SECRET \
          ACCESS_TOKEN_EXPIRES_IN REFRESH_TOKEN_EXPIRES_IN LOG_REQUESTS LOG_TO_CONSOLE \
          API_BASE_URL DOCS_USER DOCS_PASSWORD DB_HOSTNAME DB_PORT DB_USERNAME DB_PASSWORD \
          DB_NAME SALT_ROUNDS RATE_LIMITER_POINTS RATE_LIMITER_DURATION_IN_SECONDS \
          LOGIN_LIMITER_POINTS LOGIN_LIMITER_DURATION_IN_SECONDS LOGIN_LIMITER_BLOCKING_DURATION_IN_SECONDS \
          GMAIL_MAIL GMAIL_PASSWORD GOOGLE_SERVICE_ACCOUNT_KEY_LOCATION GOOGLE_CLOUD_STORAGE_BUCKET_NAME
        )

        # Dynamically assign values from GitHub Actions vars context
        # Export and interpolate each variable, with checks and quoting
        for VAR in "${VARS[@]}"; do
          GH_VAR="${VAR}_${ENV_SUFFIX}"
          # WARNING: The following uses eval to expand GitHub Actions vars context.
          eval "VALUE=\"\${{ vars.$GH_VAR }}\""
          if [ -z "$VALUE" ]; then
            echo "Required variable $GH_VAR is not set!" >&2
            exit 1
          fi
          echo "$VAR=\"$VALUE\"" >> "$GITHUB_ENV"
          if grep -q "^$VAR=" .env; then
            sed -i "s|^$VAR=.*|$VAR=\"$VALUE\"|" .env
          else
            echo "$VAR=\"$VALUE\"" >> .env
          fi
        done

        echo "ENVIRONMENT=\"$ENVIRONMENT\"" >> "$GITHUB_ENV"
        echo "COMMIT_HASH=\"$COMMIT_HASH\"" >> "$GITHUB_ENV"
        sed -i "s|^ENVIRONMENT=.*|ENVIRONMENT=\"$ENVIRONMENT\"|" .env || echo "ENVIRONMENT=\"$ENVIRONMENT\"" >> .env
        sed -i "s|^COMMIT_HASH=.*|COMMIT_HASH=\"$COMMIT_HASH\"|" .env || echo "COMMIT_HASH=\"$COMMIT_HASH\"" >> .env
        echo "Setup complete for $ENVIRONMENT ($GITHUB_REF)."
      shell: bash
