name: "Setup Environment"
description: "Sets up environment variables and creates .env from env.template"
inputs: {}
runs:
  using: "composite"
  steps:
    - run: |
        if [ "${GITHUB_REF##*/}" == "main" ]; then
          cp $GITHUB_WORKSPACE/.env.production .env
          ENVIRONMENT=production
          PROJECT_NAME=${{ vars.PROJECT_NAME_PRODUCTION }}
          NODE_ENV=${{ vars.NODE_ENV_PRODUCTION }}
          PORT=${{ vars.PORT_PRODUCTION }}
          ACCESS_TOKEN_SECRET=${{ vars.ACCESS_TOKEN_SECRET_PRODUCTION }}
          REFRESH_TOKEN_SECRET=${{ vars.REFRESH_TOKEN_SECRET_PRODUCTION }}
          ACCESS_TOKEN_EXPIRES_IN=${{ vars.ACCESS_TOKEN_EXPIRES_IN_PRODUCTION }}
          REFRESH_TOKEN_EXPIRES_IN=${{ vars.REFRESH_TOKEN_EXPIRES_IN_PRODUCTION }}
          LOG_REQUESTS=${{ vars.LOG_REQUESTS_PRODUCTION }}
          LOG_TO_CONSOLE=${{ vars.LOG_TO_CONSOLE_PRODUCTION }}
          API_BASE_URL=${{ vars.API_BASE_URL_PRODUCTION }}
          DOCS_USER=${{ vars.DOCS_USER_PRODUCTION }}
          DOCS_PASSWORD=${{ vars.DOCS_PASSWORD_PRODUCTION }}
          DB_HOSTNAME=${{ vars.DB_HOSTNAME_PRODUCTION }}
          DB_PORT=${{ vars.DB_PORT_PRODUCTION }}
          DB_USERNAME=${{ vars.DB_USERNAME_PRODUCTION }}
          DB_PASSWORD=${{ vars.DB_PASSWORD_PRODUCTION }}
          DB_NAME=${{ vars.DB_NAME_PRODUCTION }}
          SALT_ROUNDS=${{ vars.SALT_ROUNDS_PRODUCTION }}
          RATE_LIMITER_POINTS=${{ vars.RATE_LIMITER_POINTS_PRODUCTION }}
          RATE_LIMITER_DURATION_IN_SECONDS=${{ vars.RATE_LIMITER_DURATION_IN_SECONDS_PRODUCTION }}
          LOGIN_LIMITER_POINTS=${{ vars.LOGIN_LIMITER_POINTS_PRODUCTION }}
          LOGIN_LIMITER_DURATION_IN_SECONDS=${{ vars.LOGIN_LIMITER_DURATION_IN_SECONDS_PRODUCTION }}
          LOGIN_LIMITER_BLOCKING_DURATION_IN_SECONDS=${{ vars.LOGIN_LIMITER_BLOCKING_DURATION_IN_SECONDS_PRODUCTION }}
          GMAIL_MAIL=${{ vars.GMAIL_MAIL_PRODUCTION }}
          GMAIL_PASSWORD=${{ vars.GMAIL_PASSWORD_PRODUCTION }}
          GOOGLE_SERVICE_ACCOUNT_KEY_LOCATION=${{ vars.GOOGLE_SERVICE_ACCOUNT_KEY_LOCATION_PRODUCTION }}
          GOOGLE_CLOUD_STORAGE_BUCKET_NAME=${{ vars.GOOGLE_CLOUD_STORAGE_BUCKET_NAME_PRODUCTION }}
        else
          cp $GITHUB_WORKSPACE/.env.staging .env
          ENVIRONMENT=staging
          PROJECT_NAME=${{ vars.PROJECT_NAME_STAGING }}
          NODE_ENV=${{ vars.NODE_ENV_STAGING }}
          PORT=${{ vars.PORT_STAGING }}
          ACCESS_TOKEN_SECRET=${{ vars.ACCESS_TOKEN_SECRET_STAGING }}
          REFRESH_TOKEN_SECRET=${{ vars.REFRESH_TOKEN_SECRET_STAGING }}
          ACCESS_TOKEN_EXPIRES_IN=${{ vars.ACCESS_TOKEN_EXPIRES_IN_STAGING }}
          REFRESH_TOKEN_EXPIRES_IN=${{ vars.REFRESH_TOKEN_EXPIRES_IN_STAGING }}
          LOG_REQUESTS=${{ vars.LOG_REQUESTS_STAGING }}
          LOG_TO_CONSOLE=${{ vars.LOG_TO_CONSOLE_STAGING }}
          API_BASE_URL=${{ vars.API_BASE_URL_STAGING }}
          DOCS_USER=${{ vars.DOCS_USER_STAGING }}
          DOCS_PASSWORD=${{ vars.DOCS_PASSWORD_STAGING }}
          DB_HOSTNAME=${{ vars.DB_HOSTNAME_STAGING }}
          DB_PORT=${{ vars.DB_PORT_STAGING }}
          DB_USERNAME=${{ vars.DB_USERNAME_STAGING }}
          DB_PASSWORD=${{ vars.DB_PASSWORD_STAGING }}
          DB_NAME=${{ vars.DB_NAME_STAGING }}
          SALT_ROUNDS=${{ vars.SALT_ROUNDS_STAGING }}
          RATE_LIMITER_POINTS=${{ vars.RATE_LIMITER_POINTS_STAGING }}
          RATE_LIMITER_DURATION_IN_SECONDS=${{ vars.RATE_LIMITER_DURATION_IN_SECONDS_STAGING }}
          LOGIN_LIMITER_POINTS=${{ vars.LOGIN_LIMITER_POINTS_STAGING }}
          LOGIN_LIMITER_DURATION_IN_SECONDS=${{ vars.LOGIN_LIMITER_DURATION_IN_SECONDS_STAGING }}
          LOGIN_LIMITER_BLOCKING_DURATION_IN_SECONDS=${{ vars.LOGIN_LIMITER_BLOCKING_DURATION_IN_SECONDS_STAGING }}
          GMAIL_MAIL=${{ vars.GMAIL_MAIL_STAGING }}
          GMAIL_PASSWORD=${{ vars.GMAIL_PASSWORD_STAGING }}
          GOOGLE_SERVICE_ACCOUNT_KEY_LOCATION=${{ vars.GOOGLE_SERVICE_ACCOUNT_KEY_LOCATION_STAGING }}
          GOOGLE_CLOUD_STORAGE_BUCKET_NAME=${{ vars.GOOGLE_CLOUD_STORAGE_BUCKET_NAME_STAGING }}
        fi
        COMMIT_HASH=${{ github.sha }}
        # Export all variables to GITHUB_ENV
        echo "ENVIRONMENT=$ENVIRONMENT" >> $GITHUB_ENV
        echo "COMMIT_HASH=$COMMIT_HASH" >> $GITHUB_ENV
        echo "PROJECT_NAME=$PROJECT_NAME" >> $GITHUB_ENV
        echo "NODE_ENV=$NODE_ENV" >> $GITHUB_ENV
        echo "PORT=$PORT" >> $GITHUB_ENV
        echo "ACCESS_TOKEN_SECRET=$ACCESS_TOKEN_SECRET" >> $GITHUB_ENV
        echo "REFRESH_TOKEN_SECRET=$REFRESH_TOKEN_SECRET" >> $GITHUB_ENV
        echo "ACCESS_TOKEN_EXPIRES_IN=$ACCESS_TOKEN_EXPIRES_IN" >> $GITHUB_ENV
        echo "REFRESH_TOKEN_EXPIRES_IN=$REFRESH_TOKEN_EXPIRES_IN" >> $GITHUB_ENV
        echo "LOG_REQUESTS=$LOG_REQUESTS" >> $GITHUB_ENV
        echo "LOG_TO_CONSOLE=$LOG_TO_CONSOLE" >> $GITHUB_ENV
        echo "API_BASE_URL=$API_BASE_URL" >> $GITHUB_ENV
        echo "DOCS_USER=$DOCS_USER" >> $GITHUB_ENV
        echo "DOCS_PASSWORD=$DOCS_PASSWORD" >> $GITHUB_ENV
        echo "DB_HOSTNAME=$DB_HOSTNAME" >> $GITHUB_ENV
        echo "DB_PORT=$DB_PORT" >> $GITHUB_ENV
        echo "DB_USERNAME=$DB_USERNAME" >> $GITHUB_ENV
        echo "DB_PASSWORD=$DB_PASSWORD" >> $GITHUB_ENV
        echo "DB_NAME=$DB_NAME" >> $GITHUB_ENV
        echo "SALT_ROUNDS=$SALT_ROUNDS" >> $GITHUB_ENV
        echo "RATE_LIMITER_POINTS=$RATE_LIMITER_POINTS" >> $GITHUB_ENV
        echo "RATE_LIMITER_DURATION_IN_SECONDS=$RATE_LIMITER_DURATION_IN_SECONDS" >> $GITHUB_ENV
        echo "LOGIN_LIMITER_POINTS=$LOGIN_LIMITER_POINTS" >> $GITHUB_ENV
        echo "LOGIN_LIMITER_DURATION_IN_SECONDS=$LOGIN_LIMITER_DURATION_IN_SECONDS" >> $GITHUB_ENV
        echo "LOGIN_LIMITER_BLOCKING_DURATION_IN_SECONDS=$LOGIN_LIMITER_BLOCKING_DURATION_IN_SECONDS" >> $GITHUB_ENV
        echo "GMAIL_MAIL=$GMAIL_MAIL" >> $GITHUB_ENV
        echo "GMAIL_PASSWORD=$GMAIL_PASSWORD" >> $GITHUB_ENV
        echo "GOOGLE_SERVICE_ACCOUNT_KEY_LOCATION=$GOOGLE_SERVICE_ACCOUNT_KEY_LOCATION" >> $GITHUB_ENV
        echo "GOOGLE_CLOUD_STORAGE_BUCKET_NAME=$GOOGLE_CLOUD_STORAGE_BUCKET_NAME" >> $GITHUB_ENV
        # Interpolate variables into .env
        sed -i "s|^ENVIRONMENT=.*|ENVIRONMENT=$ENVIRONMENT|" .env
        sed -i "s|^COMMIT_HASH=.*|COMMIT_HASH=$COMMIT_HASH|" .env
        sed -i "s|^PROJECT_NAME=.*|PROJECT_NAME=$PROJECT_NAME|" .env
        sed -i "s|^NODE_ENV=.*|NODE_ENV=$NODE_ENV|" .env
        sed -i "s|^PORT=.*|PORT=$PORT|" .env
        sed -i "s|^ACCESS_TOKEN_SECRET=.*|ACCESS_TOKEN_SECRET=$ACCESS_TOKEN_SECRET|" .env
        sed -i "s|^REFRESH_TOKEN_SECRET=.*|REFRESH_TOKEN_SECRET=$REFRESH_TOKEN_SECRET|" .env
        sed -i "s|^ACCESS_TOKEN_EXPIRES_IN=.*|ACCESS_TOKEN_EXPIRES_IN=$ACCESS_TOKEN_EXPIRES_IN|" .env
        sed -i "s|^REFRESH_TOKEN_EXPIRES_IN=.*|REFRESH_TOKEN_EXPIRES_IN=$REFRESH_TOKEN_EXPIRES_IN|" .env
        sed -i "s|^LOG_REQUESTS=.*|LOG_REQUESTS=$LOG_REQUESTS|" .env
        sed -i "s|^LOG_TO_CONSOLE=.*|LOG_TO_CONSOLE=$LOG_TO_CONSOLE|" .env
        sed -i "s|^API_BASE_URL=.*|API_BASE_URL=$API_BASE_URL|" .env
        sed -i "s|^DOCS_USER=.*|DOCS_USER=$DOCS_USER|" .env
        sed -i "s|^DOCS_PASSWORD=.*|DOCS_PASSWORD=$DOCS_PASSWORD|" .env
        sed -i "s|^DB_HOSTNAME=.*|DB_HOSTNAME=$DB_HOSTNAME|" .env
        sed -i "s|^DB_PORT=.*|DB_PORT=$DB_PORT|" .env
        sed -i "s|^DB_USERNAME=.*|DB_USERNAME=$DB_USERNAME|" .env
        sed -i "s|^DB_PASSWORD=.*|DB_PASSWORD=$DB_PASSWORD|" .env
        sed -i "s|^DB_NAME=.*|DB_NAME=$DB_NAME|" .env
        sed -i "s|^SALT_ROUNDS=.*|SALT_ROUNDS=$SALT_ROUNDS|" .env
        sed -i "s|^RATE_LIMITER_POINTS=.*|RATE_LIMITER_POINTS=$RATE_LIMITER_POINTS|" .env
        sed -i "s|^RATE_LIMITER_DURATION_IN_SECONDS=.*|RATE_LIMITER_DURATION_IN_SECONDS=$RATE_LIMITER_DURATION_IN_SECONDS|" .env
        sed -i "s|^LOGIN_LIMITER_POINTS=.*|LOGIN_LIMITER_POINTS=$LOGIN_LIMITER_POINTS|" .env
        sed -i "s|^LOGIN_LIMITER_DURATION_IN_SECONDS=.*|LOGIN_LIMITER_DURATION_IN_SECONDS=$LOGIN_LIMITER_DURATION_IN_SECONDS|" .env
        sed -i "s|^LOGIN_LIMITER_BLOCKING_DURATION_IN_SECONDS=.*|LOGIN_LIMITER_BLOCKING_DURATION_IN_SECONDS=$LOGIN_LIMITER_BLOCKING_DURATION_IN_SECONDS|" .env
        sed -i "s|^GMAIL_MAIL=.*|GMAIL_MAIL=$GMAIL_MAIL|" .env
        sed -i "s|^GMAIL_PASSWORD=.*|GMAIL_PASSWORD=$GMAIL_PASSWORD|" .env
        sed -i "s|^GOOGLE_SERVICE_ACCOUNT_KEY_LOCATION=.*|GOOGLE_SERVICE_ACCOUNT_KEY_LOCATION=$GOOGLE_SERVICE_ACCOUNT_KEY_LOCATION|" .env
        sed -i "s|^GOOGLE_CLOUD_STORAGE_BUCKET_NAME=.*|GOOGLE_CLOUD_STORAGE_BUCKET_NAME=$GOOGLE_CLOUD_STORAGE_BUCKET_NAME|" .env

        TYPEORM_SYNCHRONIZE=${{ vars.TYPEORM_SYNCHRONIZE_PRODUCTION }}
        TYPEORM_RUN_MIGRATIONS=${{ vars.TYPEORM_RUN_MIGRATIONS_PRODUCTION }}
        WEB_SOCKET_URL=${{ vars.WEB_SOCKET_URL_PRODUCTION }}
        else
          ENVIRONMENT=staging

          
        fi
        echo "ENVIRONMENT=$ENVIRONMENT" >> $GITHUB_ENV
        sed -i "s|ENVIRONMENT=.*|ENVIRONMENT=$ENVIRONMENT|" .env
      shell: bash
